FROM php:8.4-fpm-alpine AS builder

COPY --from=composer /usr/bin/composer /usr/bin/composer

# 安装依赖并编译 Swoole
RUN \
    set -ex && \
    apk update && \
    apk add --no-cache git curl wget htop libstdc++ libpq liburing-dev libzip-dev supervisor libsodium-dev libxml2-dev yaml-dev && \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS curl-dev linux-headers brotli-dev postgresql-dev openssl-dev pcre-dev pcre2-dev sqlite-dev zlib-dev && \
    pecl channel-update pecl.php.net && \
    pecl install redis zip yaml && \
    docker-php-source extract && \
    docker-php-ext-install -j$(nproc) pdo_mysql sockets pcntl bcmath mysqli && \
    mkdir /usr/src/php/ext/swoole && \
    curl -sfL https://github.com/swoole/swoole-src/archive/v6.1.3.tar.gz -o swoole.tar.gz && \
    tar xfz swoole.tar.gz --strip-components=1 -C /usr/src/php/ext/swoole && \
    docker-php-ext-configure swoole \
        --enable-brotli \
        --enable-mysqlnd \
        --enable-openssl \
        --enable-sockets \
        --enable-swoole-curl \
        --enable-swoole-pgsql \
        --enable-swoole-sqlite \
        --enable-swoole-stdext \
        --enable-zstd && \
    docker-php-ext-install -j$(nproc) swoole && \
    docker-php-ext-enable redis zip yaml && \
    rm -f swoole.tar.gz && \
    docker-php-source delete && \
    apk del .build-deps

WORKDIR "/var/www/"