FROM php:fpm-alpine
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN apk update && apk add build-base autoconf libsodium-dev libzip-dev supervisor \
    && pecl install redis zip \
    && docker-php-ext-install pcntl pdo_mysql \
    && docker-php-ext-enable redis zip pcntl pdo_mysql