name: build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  xrayr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: XrayR-project/XrayR

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xrayr:latest

  xray:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: get-tag
        run: |
          TAG=$(curl -s "https://api.github.com/repos/XTLS/Xray-core/releases/latest" | jq -r '.tag_name')
          echo "LATEST_TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "The latest release version: $TAG"

      - name: Checkout Latest Release
        uses: actions/checkout@v4
        with:
          repository: XTLS/Xray-core
          fetch-tags: true
          ref: ${{ steps.get-tag.outputs.LATEST_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: .
          file: .github/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xray:latest,${{ secrets.DOCKERHUB_USERNAME }}/xray:${{ steps.get-tag.outputs.LATEST_TAG }}

  gitea:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: get-tag
        run: |
          TAG=$(curl -s "https://api.github.com/repos/go-gitea/gitea/releases/latest" | jq -r '.tag_name')
          echo "LATEST_TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "The latest release version: $TAG"

      - name: Checkout Latest Release
        uses: actions/checkout@v4
        with:
          repository: go-gitea/gitea
          fetch-tags: true
          ref: ${{ steps.get-tag.outputs.LATEST_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          build-args: GITEA_VERSION=${{ steps.get-tag.outputs.LATEST_TAG }}
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitea:latest,${{ secrets.DOCKERHUB_USERNAME }}/gitea:${{ steps.get-tag.outputs.LATEST_TAG }}

  gogs:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release Tag
        id: get-tag
        run: |
          TAG=$(curl -s "https://api.github.com/repos/gogs/gogs/releases/latest" | jq -r '.tag_name')
          echo "LATEST_TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "The latest release version: $TAG"

      - name: Checkout Latest Release
        uses: actions/checkout@v4
        with:
          repository: gogs/gogs
          fetch-tags: true
          ref: ${{ steps.get-tag.outputs.LATEST_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gogs:latest,${{ secrets.DOCKERHUB_USERNAME }}/gogs:${{ steps.get-tag.outputs.LATEST_TAG }}

  nps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ehang-io/nps

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Server-side and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: .
          file: Dockerfile.nps
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nps-server:latest

      - name: Build Client-side and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: .
          file: Dockerfile.npc
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nps-client:latest

  caddy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 1orz/server
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: config/caddy
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy:latest

  php-56:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 1orz/server
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: config/php-5.6
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-5.6:latest

  php-74:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 1orz/server
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: config/php-7.4
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-7.4:latest

  php-82:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 1orz/server
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: config/php-8.2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-8.2:latest
  hexo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 1orz/server
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: config/hexo
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hexo:latest
  hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: gohugoio/hugo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hugo:latest