name: Delete Outdate Workflow Runs

on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:
  
jobs:
  delete-runs:
    runs-on: ubuntu-24.04
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3
